#!/usr/bin/env bash

# Update the package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Add custom header to Nginx configuration in the default server block
sed -i "/server {/a \    add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
service nginx restart