#!/usr/bin/env bash
# load balancer configuration
# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 3.86.166.160:80 check
    server web-02 54.174.13.108:80 check
EOF'

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Restart HAProxy to apply the new configuration
sudo systemctl restart haproxy