#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure it to use round-robin algorithm to distribute requests

# Update package lists
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Create a backup of the original config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.86.166.160 check
    server web-02 54.174.13.108 check
EOF'


# Restart HAProxy service
sudo service haproxy restart
