#!/usr/bin/env bash
# bash script that configures a Nginx server to redirect '/redirect_me' to 'http://youtube.com/'
# redirection is configured as a "301 Moved Permanently"

apt-get update -y
apt-get install -y nginx


echo "Holberton School" > /etc/nginx/html/index.html

# Create a backup of the default Nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
